
== Introduction

In the first lesson this tutorial teaches you how to create an equivalence class table to define test cases.
You learn to create such a table and what the benefits of using this method are. The creation of such a table
is also called equivalence partitioning. The pool of possible input values is divided into partitions of values
to be considered the same.

For example there is a boundary that the user must be of age 18 or older. Then the input values 17 and below
are in the same class (equivalence class).

In the next lesson you convert the equivalence class table in a data generation table. In one
tool you define the test cases and create the test data needed for each test case.

At first glance it may seam a little complicated to use this method. But when you are getting familiar
with it, it is a great way.

When you define the tests with this method you also have a good documentation which tests you perform and why.
It gives the possibility to optimise test cases, find all test cases needed and avoid duplicates.

Also you can show your manager what you are doing (sometimes this is a very important factor).

The examples (files and code) used in this tutorial can be downloaded from GitHub.

----
git clone https://github.com/xhubioTable/tutorial-source.git
----

All the given references in this tutorial are relative to this repository.
